app/assignment_module/controllers.py
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from flask_session import Session
from app.helpers import *
#from tempfile import gettempdir
from app import db
from app.assignment_module.models import Assignment
from app.queries import *

# Define the blueprint
assignment_mod = Blueprint('assignment', __name__, url_prefix='/assignments' , static_folder = '../static', template_folder = '../templates/assignments')

CREATOR = 0
STUDENT = 1
class_code = None

@assignment_mod.route("/assign", methods=["GET"])
@login_required
def assign():
    if request.method == "GET" :
        user = getUserByUserID(session["user_id"])
        # global class_code
        session["class_code"] = request.args.get('class_code')
        # Get role of the user for the selected class
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignments = getAssignmentByClassCode(session["class_code"])
        class_name = getClassroomByCode(session["class_code"]).class_name
        return render_template("assignments/inside_class.html",class_code=session["class_code"],class_name=class_name,role=role, assignments=assignments)

@assignment_mod.route("/createassign", methods=["GET", "POST"])
@login_required
def createassign():

    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if role == STUDENT :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        return render_template("assignments/create_assignment.html", class_code=session["class_code"])

    if request.method == "POST" :
        doc_file = pdf_file = ppt_file = zip_file = 1
        if request.form.get('doc_file') == None :
            doc_file = 0
        if request.form.get('pdf_file') == None :
            pdf_file = 0
        if request.form.get('ppt_file') == None :
            ppt_file = 0
        if request.form.get('zip_file') == None :
            zip_file = 0

        if doc_file == 0 and pdf_file == 0 and ppt_file == 0 and zip_file == 0:
            doc_file = pdf_file = ppt_file = zip_file = 1
        new_assignment = Assignment(session["class_code"], request.form["title"], request.form["last_date"] , request.form["max_score"], request.form["description"], doc_file, pdf_file, ppt_file, zip_file)
        db.session.add(new_assignment)
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

@assignment_mod.route("/viewassign", methods=["GET", "POST"])
@login_required
def viewassign():
    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        # get role and assignment details
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignment = getAssignmentByID(session["assignment_id"])
        submission = getSubmissionByUserIDandAssignID(session["user_id"], session["assignment_id"] )
        return render_template("assignments/view_assignment.html", class_code=session["class_code"], role=role, assignment=assignment, submission=submission)

@assignment_mod.route("/editassign", methods=["GET", "POST"])
@login_required
def editassign():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if role == STUDENT :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        # get role and assignment details
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignment = getAssignmentByID(session["assignment_id"])
        return render_template("assignments/edit_assignment.html", class_code=session["class_code"], role = role, assignment = assignment)

    if request.method == "POST" :
        doc_file = pdf_file = ppt_file = zip_file = 1
        if request.form.get('doc_file') == None :
            doc_file = 0
        if request.form.get('pdf_file') == None :
            pdf_file = 0
        if request.form.get('ppt_file') == None :
            ppt_file = 0
        if request.form.get('zip_file') == None :
            zip_file = 0

        assignment = getAssignmentByID(session["assignment_id"])
        assignment.class_code = session["class_code"]
        assignment.title = request.form["title"]
        assignment.last_date = request.form["last_date"]
        assignment.max_score = request.form["max_score"],
        assignment.description = request.form["description"]
        assignment.doc_file = doc_file
        assignment.pdf_file = pdf_file
        assignment.ppt_file = ppt_file
        assignment.zip_file = zip_file
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

@assignment_mod.route("/deleteassign", methods=["GET", "POST"])
@login_required
def deleteassign():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    else :
        session["assignment_id"] = request.args.get('id')
        assignment = getAssignmentByID(session["assignment_id"])
        db.session.delete(assignment)
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

app/classroom_module/controllers.py
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from flask_session import Session
from app.helpers import *
#from tempfile import gettempdir
from app import db
from app.classroom_module.models import Classroom, User_Classroom
from app.queries import *

import random
# Define the blueprint
classroom_mod = Blueprint('classroom', __name__, url_prefix='/classes' , static_folder = '../static', template_folder = '../templates/classes')

# define role 'student' as 1
CREATOR = 0
STUDENT = 1
COLLABORATOR = 2

TEACHER = 0

@classroom_mod.route("/index", methods=["GET", "POST"])
@login_required
def index():
    if request.method == "GET" :
        # Check for existing classes
        role = getUserByUserID(session["user_id"]).role
        joined_classes = getJoinedClassroom(session["user_id"], db.session)
        created_classes = getCreatedClassroom(session["user_id"], db.session)
        if role == 1 :
            return render_template("classes/main_class.html", role=role, classes=joined_classes)
        else :
            return render_template("classes/main_class.html", role=role, classes=created_classes)

    if request.method == "POST" :
        # Check whether the entered class code is valid
        if (getClassroomByCode(request.form["class_code"]) == None ) :
            return render_template("auth/no_access.html", msg="Incorrect Class Code")

        # Check whether student is already a part of the classroom
        user_class = getUser_ClassroomByCodeAndID(session["user_id"],request.form["class_code"])
        if (user_class != None):
            if user_class.role == STUDENT :
                return render_template("auth/no_access.html", msg="Already part of this class")
            else :
                return render_template("auth/no_access.html", msg="You are creator of this class")

        # Add the student to the classroom
        user_class = User_Classroom( session["user_id"], request.form["class_code"], STUDENT)
        db.session.add(user_class)
        db.session.commit()
        return redirect(url_for("classroom.index"))

@classroom_mod.route("/joined_classes", methods=["GET", "POST"])
@login_required
def joined_classes():
    if request.method == "GET" :
        # Check for existing classes
        role = getUserByUserID(session["user_id"]).role
        joined_classes = getJoinedClassroom(session["user_id"], db.session)
        if role == 0 :
            return render_template("classes/main_class.html", role=  role, classes=joined_classes)

@classroom_mod.route("/createclass", methods=["GET", "POST"])
@login_required
def createclass():
    user = getUserByUserID(session["user_id"])
    # Only teachers can create class
    if  user.role != TEACHER :
        return render_template("auth/no_access.html",msg="You do not have access to this page !")

    if request.method == "GET" :
        #check with db that code is unique
        invalid = True
        while(invalid):
            code = random.randint(10000, 99999)
            if getClassroomByCode(code) == None :
                invalid = False

        session["join_code"] = code
        return render_template("classes/create_class.html", code=code)

    if request.method == "POST" :
        new_class = Classroom(session["join_code"], session["user_id"], request.form["class_name"], request.form["subject"], request.form["sub_code"], request.form["credits"],request.form["semester"],request.form["description"])
        db.session.add(new_class)
        db.session.commit()
        user_class = User_Classroom( session["user_id"], session["join_code"], CREATOR)
        db.session.add(user_class)
        db.session.commit()

        return redirect(url_for("classroom.index"))

@classroom_mod.route("/leaveclass", methods=["GET", "POST"])
@login_required
def leaveclass():
    user_classroom = getUser_ClassroomByCodeAndID(session['user_id'], session['class_code'])
    db.session.delete(user_classroom)
    db.session.commit()
    submissions = getSubmissionsByUserIDandClassCode(session['user_id'], session['class_code'])
    for submission in submissions:
        db.session.delete(submission)
        db.session.commit()
    return redirect(url_for("classroom.index"))

@classroom_mod.route("/deleteclass", methods=["GET", "POST"])
@login_required
def deleteclass():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    # Only creators can delete class
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    else :
        classroom = getClassroomByCode(session['class_code'])
        db.session.delete(classroom)
        db.session.commit()
        return redirect(url_for("classroom.index"))

@classroom_mod.route("/students", methods=["GET", "POST"])
@login_required
def students():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        students = getStudentDetails(session["class_code"])
        classroom = getClassroomByCode(session["class_code"])
        return render_template("assignments/students.html", students=students, role=role, classroom=classroom)

    if request.method == "POST" :
        user_id = request.args.get('user_id')
        class_code = request.args.get('class_code')
        user_classroom = getUser_ClassroomByCodeAndID(user_id, class_code)
        db.session.delete(user_classroom)
        db.session.commit()
        return redirect(url_for('classroom.students'))

@classroom_mod.route("/class_gradebook", methods=["GET"])
@login_required
def class_gradebook():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        students = getStudentDetails(session["class_code"])
        classroom = getClassroomByCode(session["class_code"])
        assignments = getAssignmentByClassCode(session["class_code"])

        gradebook = {}
        for assignment in assignments:
            submissions = getSubmissionByAssignID(assignment.assignment_id)
            assignment_id = assignment.assignment_id
            gradebook[assignment_id] = {}
            for submission in submissions:
                user_id = submission.user_id
                gradebook[assignment_id][user_id] = submission.grade
                print(gradebook[assignment_id][user_id])
            print()
        #gradebook = getGradebook(assignments)
        return render_template("classes/class_gradebook.html", students=students,role=role,classroom=classroom,assignments=assignments,gradebook=gradebook)

app/templates/assignments/add_assign_fab.html
<div>
    <a href="{{url_for("assignment.createassign")}}">
        <button id="add_assign_fab" type="button"  class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored md-fab-bottom-right">
            <i class="material-icons">add</i>
        </button>
    </a>
</div>

app/templates/assignments/all_assignments.html
<div class="page-content">
        <div id="all_assign_body" class="class_grid">
            <!-- Square card -->
            {% for assignment in assignments %}
              {% include "assignment_card.html" %}
            {% endfor %}
        </div>
</div>

app/templates/assignments/assign_nav_drawer.html
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    {% include "header.html" %}
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Classroom</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{{url_for('assignment.assign', class_code=session['class_code'])}}">Assignments</a>
            <a class="mdl-navigation__link" href="">Notes</a>
            {% if role is equalto 0%}
            <a class="mdl-navigation__link" href="{{url_for('classroom.class_gradebook')}}">Gradebook</a>
            <a class="mdl-navigation__link" href="{{url_for('classroom.students')}}">Students</a>
            <a class="mdl-navigation__link" href="{{url_for('classroom.deleteclass')}}">Delete Classroom</a>
            {% elif role is equalto 1%}
            <a class="mdl-navigation__link" href="{{url_for('submission.student_gradebook')}}">Gradebook</a>
            <a class="mdl-navigation__link" href="{{url_for('classroom.leaveclass')}}">Leave Classroom</a>
            {% endif %}
        </nav>
    </div>
</div>

app/templates/assignments/assignment_card.html
<div class="mdl-card mdl-shadow--2dp demo-card-square">
    <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text">{{assignment.title}}</h2>
    </div>
    <div class="mdl-card__supporting-text text_area">
        <div> <b>Last Date : </b>{{ assignment.last_date }} </div>
        <div><b> Max Score : </b>{{ assignment.max_score }} </div>
        <div> {{assignment.description}} </div>
    </div>
    <div class="mdl-card__actions mdl-card--border">
        {% if role is equalto 0 %}
        <a href="{{url_for('assignment.editassign', id=assignment.assignment_id)}}" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
          Edit  </a>
        <a href="{{url_for('submission.view_submissions', id=assignment.assignment_id)}}" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
          View  </a>

         {% elif role is equalto 1 %}
         <a href="{{url_for('assignment.viewassign', id=assignment.assignment_id)}}" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
            View  </a>
        {% endif %}
    </div>
</div>

app/templates/assignments/create_assignment.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='assignment.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}

{% block title %} Create Assignment {% endblock %}

{% block body %}
{% include "assign_nav_drawer.html" %}
<br><br><br>

<main id="form_main" class="web-main mdl-layout__content">
    <!-- <div id="form" class="web-container mdl-grid"> -->
    <br><br><br>
    <div class="mdl-grid portfolio-max-width">


        <!-- <div class="mdl-grid portfolio-max-width"> -->
    <div class="mdl-cell mdl-cell--4-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <!-- <div class="web-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--4-col portfolio-max-width"> -->
        <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--4dp">
           <!-- <div id="assign_back" class="mdl-card__media">
               <img class="article-image" border="0" alt="">
           </div> -->

          <div id="form_create_assign">

               <h3>Create Assignment</h3>
               <form method="POST" action="{{url_for("assignment.createassign")}}">
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="text" name="title" placeholder="Title" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="number" name="max_score" placeholder="Max Score" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="date" name="last_date" placeholder="Last Date" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <textarea class="mdl-textfield__input" type="text" rows= "4" name="description" placeholder="Description" required></textarea>
                 </div>

                <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" disabled name="" placeholder="Supported File Formats" >
                </div>
                <div>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
                        <!-- <input type="hidden" name="doc_file" value=0 > -->
                        <input type="checkbox" id="checkbox-1" name="doc_file" value=1 class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.doc</span>
                    </label>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-2">
                        <!-- <input type="hidden" name="pdf_file" value=0 > -->
                        <input type="checkbox" id="checkbox-2" name="pdf_file" value=1 class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.pdf</span>
                    </label>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-3">
                        <!-- <input type="hidden" name="ppt_file" value=0 > -->
                        <input type="checkbox" id="checkbox-3" name="ppt_file" value=1 class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.ppt</span>
                    </label>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-4">
                        <!-- <input type="hidden" name="zip_file" value=0 > -->
                        <input type="checkbox" id="checkbox-4" name="zip_file" value=1 class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.zip</span>
                    </label>
                </div>
                <br><br>
                    <input type="submit" class="rc-button rc-button-submit" value="Submit">
                </form><br>
            </div>
        </div>
   </div>
</main>

{% endblock %}

app/templates/assignments/edit_assignment.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='assignment.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}

{% block title %} Edit Assignment {% endblock %}

{% block body %}
{% include "assign_nav_drawer.html" %}
<br><br><br>

<main id="form_main" class="web-main mdl-layout__content">
    <!-- <div id="form" class="web-container mdl-grid"> -->
    <br><br><br>
    <div class="mdl-grid portfolio-max-width">


        <!-- <div class="mdl-grid portfolio-max-width"> -->
    <div class="mdl-cell mdl-cell--4-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <!-- <div class="web-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--4-col portfolio-max-width"> -->
        <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--4dp">
           <!-- <div id="assign_back" class="mdl-card__media">
               <img class="article-image" border="0" alt="">
           </div> -->

          <div id="form_create_assign">

               <h3>Edit Assignment</h3>
               <form method="POST" action="{{url_for("assignment.editassign")}}">
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="text" name="title" placeholder="Title" value="{{assignment.title}}" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="number" name="max_score" placeholder="Max Score" value="{{assignment.max_score}}" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="date" name="last_date" placeholder="Last Date" value="{{assignment.last_date}}" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <textarea class="mdl-textfield__input" type="text" rows= "4" name="description" placeholder="Description" required>{{assignment.description}}</textarea>
                 </div>

                <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" disabled name="" placeholder="Supported File Formats" >
                </div>
                <div>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
                        <input type="checkbox" id="checkbox-1" name="doc_file" value=1 {% if assignment.doc_file is equalto 1 %} checked {% endif %} class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.doc</span>
                    </label>

                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-2">
                        <input type="checkbox" id="checkbox-2" name="pdf_file" value=1 {% if assignment.pdf_file is equalto 1 %} checked {% endif %} class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.pdf</span>
                    </label>

                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-3">
                        <input type="checkbox" id="checkbox-3" name="ppt_file" value=1 {% if assignment.ppt_file is equalto 1 %} checked {% endif %}  class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.ppt</span>
                    </label>

                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-4">
                        <input type="checkbox" id="checkbox-4" name="zip_file" value=1 {% if assignment.zip_file is equalto 1 %} checked {% endif %} class="mdl-checkbox__input">
                        <span class="mdl-checkbox__label">.zip</span>
                    </label>

                </div>
                <br><br>
                    <input type="submit" class="rc-button rc-button-submit" value="Edit">
                </form><br>
            </div>
        </div>
   </div>
</main>

{% endblock %}

app/templates/assignments/inside_class.html
{% extends "layout.html" %} {% block head %}
<link href="{{ url_for('static', filename='assignment.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css"> {% endblock %} {% block title %} Assignment {% endblock %} {% block body %} {% include "assign_nav_drawer.html" %}
<div id="class_title">
    <h3>{{class_name}}</h3>
</div>
<main id="main-content" class="mdl-layout__content">

    {% if assignments %} {% include "all_assignments.html" %} {% else %} {% include "no_assignments.html" %} {% endif %} {% if role is equalto 0 %} {% include "add_assign_fab.html" %} {% endif %}

</main>
{% endblock %}

app/templates/assignments/no_assignments.html
<div id="welcome_card" class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Welcome</h2>
        </div>
        <div class="mdl-card__supporting-text">
        You do not have any assignments yet.
        {% if role is equalto 0 %}
             Click on the button below to add an assignment.
        {% endif %}
        </div>
</div>

app/templates/assignments/students.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='submission.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}
{% block title %} Students {% endblock %}

{% block body %}
{% include "./assignments/assign_nav_drawer.html" %}
<div id="assignment_title"><h3>{{classroom.class_name}} - Students</h3> </div>
  <main id="page_body">
      <table id="submission_table" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
          <thead>
              <tr>
                  <th>S No.</th>
                  <th>Name</th>
                  <th>UID</th>
                  <th>Email</th>
                  <th>Remove Student</th>
              </tr>
          </thead>
          <tbody>
              {% for student in students%}
              <form action="{{url_for('classroom.students', user_id=student[0], class_code=classroom.class_code)}}" method="post">
                <tr>
                  <td>{{loop.index}}</td>
                  <td>{{student[1]}}</td>
                  <td>{{student[2]}}</td>
                  <td>{{student[3]}}</td>
                  <td>
                      <button  type="submit" class="mdl-button mdl-js-button mdl-button--icon">
                        <i class="material-icons">close</i>
                      </button>
                  </td>
                </tr>
              </form>
              {% endfor %}
        </tbody>
  </main>
{% endblock %}

app/templates/assignments/view_assignment.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='assignment.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}

{% block title %} View Assignment {% endblock %}

{% block body %}
{% include "assign_nav_drawer.html" %}
<br><br><br><br>

<main class="web-main mdl-layout__content">
  <div class="web-container mdl-grid">
  <!-- <div class="mdl-grid portfolio-max-width"> -->
    <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <div class="mdl-card mdl-shadow--4dp  mdl-cell mdl-cell--8-col">
           <!-- <div class="mdl-card__title">
               <h2 class="mdl-card__title-text">Java Assignment</h2>
           </div> -->
           <div id="assign_back" class="mdl-card__media">
               <img class="article-image" border="0" alt="">
           </div>

          <div id="view_assign">
             <h2>{{assignment.title}} </h2>

             {% if role is equalto 1 %}
             <p id="link"> File Submitted:
                 {% if submission %}
                 <a style="color:#009688"
                    href="{{url_for('submission.uploaded_file', assign_id=assignment.assignment_id, filename=submission.filename)}}">
                    {{submission.filename}}</a>
                 {% else %}
                  None
                 {% endif %}
             </p>
             {% endif %}

               <h4>Description</h4>
               <div  class="assign_text">
                   <p> {{assignment.description}}</p>
               </div>
               <h4>Details</h4>
               <div class="assign_text">
                   <p> Last Date: {{assignment.last_date}}</p>
                   <p> Maximum Score: {{assignment.max_score}}</p>
                   <p> File Formats:
                       {% if assignment.pdf_file is equalto 1 %} .pdf {% endif %}
                       {% if assignment.doc_file is equalto 1 %} .doc {% endif %}
                       {% if assignment.ppt_file is equalto 1 %} .ppt {% endif %}
                       {% if assignment.zip_file is equalto 1 %} .zip {% endif %}
               </div>
           </div>
       </div>
   </div>

  <!-- Accent-colored raised button with ripple -->
  {% if role is equalto 1 %}
        {% include "./submissions/upload_file_dialog.html" %}
  {% endif %}
</main>
<script src="{{ url_for('static', filename='submission.js') }}" type= "text/javascript" ></script>
{% endblock %}