app/classroom_module/controllers.py
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from flask_session import Session
from app.helpers import *
#from tempfile import gettempdir
from app import db
from app.classroom_module.models import Classroom, User_Classroom
from app.queries import *

import random
# Define the blueprint
classroom_mod = Blueprint('classroom', __name__, url_prefix='/classes' , static_folder = '../static', template_folder = '../templates/classes')

# define role 'student' as 1
CREATOR = 0
STUDENT = 1
COLLABORATOR = 2

TEACHER = 0

@classroom_mod.route("/index", methods=["GET", "POST"])
@login_required
def index():
    if request.method == "GET" :
        # Check for existing classes
        role = getUserByUserID(session["user_id"]).role
        joined_classes = getJoinedClassroom(session["user_id"], db.session)
        created_classes = getCreatedClassroom(session["user_id"], db.session)
        if role == 1 :
            return render_template("classes/main_class.html", role=role, classes=joined_classes)
        else :
            return render_template("classes/main_class.html", role=role, classes=created_classes)

    if request.method == "POST" :
        # Check whether the entered class code is valid
        if (getClassroomByCode(request.form["class_code"]) == None ) :
            return render_template("auth/no_access.html", msg="Incorrect Class Code")

        # Check whether student is already a part of the classroom
        user_class = getUser_ClassroomByCodeAndID(session["user_id"],request.form["class_code"])
        if (user_class != None):
            if user_class.role == STUDENT :
                return render_template("auth/no_access.html", msg="Already part of this class")
            else :
                return render_template("auth/no_access.html", msg="You are creator of this class")

        # Add the student to the classroom
        user_class = User_Classroom( session["user_id"], request.form["class_code"], STUDENT)
        db.session.add(user_class)
        db.session.commit()
        return redirect(url_for("classroom.index"))

@classroom_mod.route("/joined_classes", methods=["GET", "POST"])
@login_required
def joined_classes():
    if request.method == "GET" :
        # Check for existing classes
        role = getUserByUserID(session["user_id"]).role
        joined_classes = getJoinedClassroom(session["user_id"], db.session)
        if role == 0 :
            return render_template("classes/main_class.html", role=  role, classes=joined_classes)

@classroom_mod.route("/createclass", methods=["GET", "POST"])
@login_required
def createclass():
    user = getUserByUserID(session["user_id"])
    # Only teachers can create class
    if  user.role != TEACHER :
        return render_template("auth/no_access.html",msg="You do not have access to this page !")

    if request.method == "GET" :
        #check with db that code is unique
        invalid = True
        while(invalid):
            code = random.randint(10000, 99999)
            if getClassroomByCode(code) == None :
                invalid = False

        session["join_code"] = code
        return render_template("classes/create_class.html", code=code)

    if request.method == "POST" :
        new_class = Classroom(session["join_code"], session["user_id"], request.form["class_name"], request.form["subject"], request.form["sub_code"], request.form["credits"],request.form["semester"],request.form["description"])
        db.session.add(new_class)
        db.session.commit()
        user_class = User_Classroom( session["user_id"], session["join_code"], CREATOR)
        db.session.add(user_class)
        db.session.commit()

        return redirect(url_for("classroom.index"))

@classroom_mod.route("/leaveclass", methods=["GET", "POST"])
@login_required
def leaveclass():
    user_classroom = getUser_ClassroomByCodeAndID(session['user_id'], session['class_code'])
    db.session.delete(user_classroom)
    db.session.commit()
    submissions = getSubmissionsByUserIDandClassCode(session['user_id'], session['class_code'])
    for submission in submissions:
        db.session.delete(submission)
        db.session.commit()
    return redirect(url_for("classroom.index"))

@classroom_mod.route("/deleteclass", methods=["GET", "POST"])
@login_required
def deleteclass():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    # Only creators can delete class
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    else :
        classroom = getClassroomByCode(session['class_code'])
        db.session.delete(classroom)
        db.session.commit()
        return redirect(url_for("classroom.index"))

@classroom_mod.route("/students", methods=["GET", "POST"])
@login_required
def students():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        students = getStudentDetails(session["class_code"])
        classroom = getClassroomByCode(session["class_code"])
        return render_template("assignments/students.html", students=students, role=role, classroom=classroom)

    if request.method == "POST" :
        user_id = request.args.get('user_id')
        class_code = request.args.get('class_code')
        user_classroom = getUser_ClassroomByCodeAndID(user_id, class_code)
        db.session.delete(user_classroom)
        db.session.commit()
        return redirect(url_for('classroom.students'))

@classroom_mod.route("/class_gradebook", methods=["GET"])
@login_required
def class_gradebook():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        students = getStudentDetails(session["class_code"])
        classroom = getClassroomByCode(session["class_code"])
        assignments = getAssignmentByClassCode(session["class_code"])

        gradebook = {}
        for assignment in assignments:
            submissions = getSubmissionByAssignID(assignment.assignment_id)
            assignment_id = assignment.assignment_id
            gradebook[assignment_id] = {}
            for submission in submissions:
                user_id = submission.user_id
                gradebook[assignment_id][user_id] = submission.grade
                print(gradebook[assignment_id][user_id])
            print()
        #gradebook = getGradebook(assignments)
        return render_template("classes/class_gradebook.html", students=students,role=role,classroom=classroom,assignments=assignments,gradebook=gradebook)

app/templates/classes/add_class_fab.html
<div class="dropdown">
    <button id="add_class_fab" type=button onclick="displayMenu()" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored md-fab-bottom-right">
        <i class="material-icons">add</i>
    </button>
    <div id="fabDropdown" class="dropdown-content">
        <a onclick="displayDialog()">Join Classroom</a>
        <a href="{{url_for('classroom.createclass')}}">Add Classroom</a>
    </div>
</div>

app/templates/classes/card.html
<div class="mdl-card mdl-shadow--2dp demo-card-square">
    <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text">{{ class.class_name }}</h2>
    </div>
    <div class="mdl-card__supporting-text text_area" >
      <div> <b>Class Code : </b>{{ class.class_code }} </div>
      <div><b> Semester : </b>{{ class.semester }} </div>
      {% if role == "Creator"%}
        <div><b> Creator </b></div>
      {% else %}
        <div><b> Student </b></div>
      {% endif %}
      <div > {{ class.description }} </div>


    </div>
    <div class="mdl-card__actions mdl-card--border">
        <a href="{{url_for('assignment.assign', class_code=class.class_code)}}" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
                  View
        </a>
    </div>
</div>

app/templates/classes/class_card.html
<div class="mdl-card mdl-shadow--2dp demo-card-square">
    <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text">{{ class.class_name }}</h2>
    </div>
    <div class="mdl-card__supporting-text text_area" >
      <div> <b>Class Code : </b>{{ class.class_code }} </div>
      <div><b> Semester : </b>{{ class.semester }} </div>
     <div > {{ class.description }} </div>

    </div>
    <div class="mdl-card__actions mdl-card--border">
        <a href="{{url_for('assignment.assign', class_code=class.class_code)}}" class="mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect">
                  View
        </a>
    </div>
</div>

app/templates/classes/class_gradebook.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='submission.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}
{% block title %} View Grades {% endblock %}

{% block body %}
{% include "./assignments/assign_nav_drawer.html" %}
<div id="assignment_title"><h3>{{classroom.class_name}} - Gradebook</h3> </div>
  <main id="page_body">
      <table id="submission_table" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
          <thead>
              <tr style="height:70px">
                  <th>S No.</th>
                  <th>Name</th>
                  <th>UID</th>
                  {% for assignment in assignments %}
                    <th>{{assignment.title}}<br>({{assignment.max_score}})</th>
                  {% endfor %}
              </tr>
          </thead>
          <tbody>
              {% for student in students %}
                <tr>
                  <td>{{loop.index}}</td>
                  <td>{{student[1]}}</td>
                  <td >{{student[2]}}</td>
                  {% for assignment in assignments %}
                    {% if gradebook[assignment.assignment_id][student[0]] %}
                    <td>{{gradebook[assignment.assignment_id][student[0]]}}</td>
                    {% else %}
                    <td>Not Submitted</td>
                    {% endif %}
                  {% endfor %}
                </tr>
              {% endfor %}
        </tbody>
  </main>
{% endblock %}

app/templates/classes/class_nav_drawer.html
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    {% include "header.html" %}
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Classroom</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{{url_for('classroom.index')}}">Classes</a>
            {% if role is equalto 0 %}
            <a class="mdl-navigation__link" href="{{url_for('classroom.joined_classes')}}">Joined Classes</a>
            {% endif %}
            <a class="mdl-navigation__link" href="#">Calendar</a>
            <a class="mdl-navigation__link" href="#">Work</a>

            {% if role is equalto 0 %}
            <a class="mdl-navigation__link" href="#">Edit Details</a>
            {% elif role is equalto 1 %}
            <a class="mdl-navigation__link" href="#">Edit Details</a>
            {% endif %}

        </nav>
    </div>
</div>

app/templates/classes/classes.html
<div class="page-content">
        <div id="class_body" class="class_grid">
            <!-- Square card -->
            <div>
              {% for class in classes %}
                {% include "class_card.html" %}
              {% endfor %}
            </div>

        </div>
</div>

app/templates/classes/classroom.html
<div class="page-content">
        <div id="class_body" class="class_grid">
            <!-- Square card -->
            <div>
              {% if role is equalto 0 %}
                   <!-- <p>classes created </p> -->
                   <!-- <br> -->
                   {% for class in created_classes %}
                      {% with role="Creator" %}
                        {% include "card.html" %}
                      {% endwith %}
                   {% endfor %}
                   <!-- <br> -->
              {% endif %}
            </div>

            <div>
              <!-- <p> Classes joined </p> -->
              {% for class in joined_classes %}
                {% include "card.html" %}
                <!-- {% for class in x %} -->
                <!-- {% endfor %} -->
              {% endfor %}
            </div>

        </div>
</div>

app/templates/classes/create_class.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='classroom.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}

{% block title %} Create Class {% endblock %}

{% block body %}
{% include "class_nav_drawer.html" %}
<br><br><br>

<main id="form_main" class="web-main mdl-layout__content">
    <!-- <div id="form" class="web-container mdl-grid"> -->
    <br><br><br>
    <div class="mdl-grid portfolio-max-width">


        <!-- <div class="mdl-grid portfolio-max-width"> -->
    <div class="mdl-cell mdl-cell--4-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <!-- <div class="web-content mdl-color--white mdl-shadow--4dp content mdl-color-text--grey-800 mdl-cell mdl-cell--4-col portfolio-max-width"> -->
        <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--4dp">
           <!-- <div id="assign_back" class="mdl-card__media">
               <img class="article-image" border="0" alt="">
           </div> -->

          <div id="form_create_class">

               <h3>Create a Class</h3>
               <form method="POST" action="{{url_for("classroom.createclass")}}">
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="text" name="class_name" placeholder="Name of the Class" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="text" name="subject" placeholder="Subject" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="text" name="sub_code" placeholder="Course Code" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="number" name="credits" placeholder="Credits" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <input class="mdl-textfield__input" type="number" name="semester" placeholder="Semester" required>
                 </div>
                 <div class="mdl-textfield mdl-js-textfield">
                     <textarea class="mdl-textfield__input" type="text" rows= "4" name="description" placeholder="Description" required></textarea>
                 </div>
                 <h5>Class Code: {{code}}</h5><br>
                 <input type="submit" class="rc-button rc-button-submit" value="Submit">
             </form><br>


       </div>
   </div>
   </div>

</main>

{% endblock %}

app/templates/classes/join_class_dialog.html
<dialog id = "join_class_dialog" class="mdl-dialog">
    <h5>Join a Class</h5><br>
    <form method="POST" action="{{url_for("classroom.index")}}">
      <div class="mdl-textfield mdl-js-textfield">
         <input class="mdl-textfield__input" type="number" min="10000" max="99999" name="class_code" placeholder="Class Code" required>
      </div>
      <br>
      <div class="mdl-dialog__actions">
        <input type="submit" value="Join" class="mdl-button create"></button>
        <button type="button" class="mdl-button cancel">Cancel</button>
      </div>
    </form>
</dialog>

app/templates/classes/join_class_fab.html
<div>
    <button id="join_class_fab" type=button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored md-fab-bottom-right">
        <i class="material-icons">add</i>
    </button>
</div>

app/templates/classes/main_class.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='classroom.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
<!-- <script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script> -->
{% endblock %}

{% block title %} Classroom {% endblock %}

{% block body %}

{% include "class_nav_drawer.html" %}

<main id="main-content" class="mdl-layout__content">

<!-- Check the role and whether the user has joined/created any classes -->
{% if classes %}
    {% include "classes.html" %}
{% else %}
    {% include "no_classes.html" %}
{% endif%}

{% if role is equalto 0 %}
    {% include "add_class_fab.html" %}
{% elif role is equalto 1 %}
    {% include "join_class_fab.html" %}
{% endif %}
{% include "join_class_dialog.html" %}
</main>
<script src="{{ url_for('static', filename='classroom.js') }}" type= "text/javascript" ></script>
{% endblock %}

app/templates/classes/no_classes.html
<div id="welcome_card" class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Welcome</h2>
        </div>
        <div class="mdl-card__supporting-text">
        You do not have any classrooms yet. Click on the button below to join {% if role is equalto 0 %}or add{% endif %} a classroom.
        </div>
</div>

app/templates/classes/no_classroom.html
<div id="welcome_card" class="demo-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Welcome</h2>
        </div>
        <div class="mdl-card__supporting-text">
        You do not have any classrooms yet. Click on the button below to join a classroom.
        </div>
</div>