app/assignment_module/controllers.py
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from flask_session import Session
from app.helpers import *
#from tempfile import gettempdir
from app import db
from app.assignment_module.models import Assignment
from app.queries import *

# Define the blueprint
assignment_mod = Blueprint('assignment', __name__, url_prefix='/assignments' , static_folder = '../static', template_folder = '../templates/assignments')

CREATOR = 0
STUDENT = 1
class_code = None

@assignment_mod.route("/assign", methods=["GET"])
@login_required
def assign():
    if request.method == "GET" :
        user = getUserByUserID(session["user_id"])
        # global class_code
        session["class_code"] = request.args.get('class_code')
        # Get role of the user for the selected class
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignments = getAssignmentByClassCode(session["class_code"])
        class_name = getClassroomByCode(session["class_code"]).class_name
        return render_template("assignments/inside_class.html",class_code=session["class_code"],class_name=class_name,role=role, assignments=assignments)

@assignment_mod.route("/createassign", methods=["GET", "POST"])
@login_required
def createassign():

    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if role == STUDENT :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        return render_template("assignments/create_assignment.html", class_code=session["class_code"])

    if request.method == "POST" :
        doc_file = pdf_file = ppt_file = zip_file = 1
        if request.form.get('doc_file') == None :
            doc_file = 0
        if request.form.get('pdf_file') == None :
            pdf_file = 0
        if request.form.get('ppt_file') == None :
            ppt_file = 0
        if request.form.get('zip_file') == None :
            zip_file = 0

        if doc_file == 0 and pdf_file == 0 and ppt_file == 0 and zip_file == 0:
            doc_file = pdf_file = ppt_file = zip_file = 1
        new_assignment = Assignment(session["class_code"], request.form["title"], request.form["last_date"] , request.form["max_score"], request.form["description"], doc_file, pdf_file, ppt_file, zip_file)
        db.session.add(new_assignment)
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

@assignment_mod.route("/viewassign", methods=["GET", "POST"])
@login_required
def viewassign():
    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        # get role and assignment details
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignment = getAssignmentByID(session["assignment_id"])
        submission = getSubmissionByUserIDandAssignID(session["user_id"], session["assignment_id"] )
        return render_template("assignments/view_assignment.html", class_code=session["class_code"], role=role, assignment=assignment, submission=submission)

@assignment_mod.route("/editassign", methods=["GET", "POST"])
@login_required
def editassign():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if role == STUDENT :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        # get role and assignment details
        role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
        assignment = getAssignmentByID(session["assignment_id"])
        return render_template("assignments/edit_assignment.html", class_code=session["class_code"], role = role, assignment = assignment)

    if request.method == "POST" :
        doc_file = pdf_file = ppt_file = zip_file = 1
        if request.form.get('doc_file') == None :
            doc_file = 0
        if request.form.get('pdf_file') == None :
            pdf_file = 0
        if request.form.get('ppt_file') == None :
            ppt_file = 0
        if request.form.get('zip_file') == None :
            zip_file = 0

        assignment = getAssignmentByID(session["assignment_id"])
        assignment.class_code = session["class_code"]
        assignment.title = request.form["title"]
        assignment.last_date = request.form["last_date"]
        assignment.max_score = request.form["max_score"],
        assignment.description = request.form["description"]
        assignment.doc_file = doc_file
        assignment.pdf_file = pdf_file
        assignment.ppt_file = ppt_file
        assignment.zip_file = zip_file
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

@assignment_mod.route("/deleteassign", methods=["GET", "POST"])
@login_required
def deleteassign():
    role = getUser_ClassroomByCodeAndID(session["user_id"], session["class_code"]).role
    if  role != CREATOR :
        return render_template("auth/no_access.html", msg="You do not have access to this page !")

    else :
        session["assignment_id"] = request.args.get('id')
        assignment = getAssignmentByID(session["assignment_id"])
        db.session.delete(assignment)
        db.session.commit()
        return redirect(url_for("assignment.assign", class_code=session["class_code"]))

app/submission_module/controllers.py
import os
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint, send_from_directory
from flask_session import Session
from werkzeug import secure_filename
from datetime import datetime

from app.helpers import *
from app import db
from app.queries import *
from app import app
from app.submission_module.models import Submission

# Define the blueprint
submission_mod = Blueprint('submission', __name__, url_prefix='/submissions' , static_folder = '../static', template_folder = '../templates/submissions')

# For a given file, return whether it's an allowed type or not
def allowed_file(filename, extensions):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in extensions

def getExtensions(assignment):
    extensions = []
    if ( assignment.pdf_file == 1 ):
        extensions.extend(["pdf"])
    if ( assignment.doc_file == 1 ):
        extensions.extend(["doc", "docx"])
    if ( assignment.zip_file == 1 ):
        extensions.extend(["zip"])
    if (assignment.ppt_file == 1 ):
        extensions.extend(["ppt", "pptx"])
    return extensions

@submission_mod.route("/upload", methods=["GET", "POST"])
@login_required
def upload():
    if request.method == "POST":

        id = request.args.get('id')
        assignment = getAssignmentByID(id)
        username = getUserByUserID(session["user_id"]).username
        extensions = getExtensions(assignment)

        file = request.files['file']
        # Check if the file is one of the allowed types/extensions
        #TODO handle else condition
        if file and allowed_file(file.filename, extensions):
            # Make the filename safe, remove unsupported chars
            filename = secure_filename(username + "_" + file.filename)
            # Move the file form the temporal folder to the upload folder we setup
            abs_filepath = os.path.join(os.path.abspath(app.config['UPLOAD_FOLDER']), str(id), filename)
            #Beware of Race Condition
            directory = os.path.dirname(abs_filepath)
            if not os.path.exists(directory):
                os.makedirs(directory)
            # Save file
            file.save(abs_filepath)

            submission = getSubmissionByUserIDandAssignID(session['user_id'], id)
            grade = '-'
            file_format = filename.rsplit('.', 1)[1]
            rel_filepath = os.path.join(app.config['UPLOAD_FOLDER'], str(id))
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            if submission == None:
                new_submission = Submission(timestamp, session["user_id"], assignment.class_code, id, grade, file_format, filename, rel_filepath)
                db.session.add(new_submission)
                db.session.commit()
            else :
                submission.timestamp = timestamp
                submission.file_format = file_format
                submission.filename = filename
                submission.filepath = rel_filepath
                db.session.commit()

            # return redirect(url_for('submission.uploaded_file', filename=filename, assign_id=id))
            return redirect(url_for('assignment.viewassign', id=session["assignment_id"]))
        else:
            return render_template("auth/no_access.html", msg="File extension not allowed, Please upload one of these formats: " + str(extensions))

@submission_mod.route('/uploads/<filename>')
def uploaded_file(filename):
    assign_id = request.args.get('assign_id')
    submission = getSubmissionByUserIDandAssignID(session['user_id'], assign_id)
    return send_from_directory(os.path.abspath(submission.filepath), submission.filename)

@submission_mod.route('/view_file/<filename>')
def view_file(filename):
    filepath = request.args.get('filepath')
    return send_from_directory(os.path.abspath(filepath), filename)

@submission_mod.route('/view_submissions', methods=["GET","POST"])
def view_submissions():
    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        submissions_data = getSubmissionsForAssign(session["assignment_id"])
        assigment = getAssignmentByID(session["assignment_id"])
        return render_template("submissions/view_submission_teacher.html", assignment=assigment, submissions = submissions_data)

@submission_mod.route('/student_gradebook', methods=["GET","POST"])
def student_gradebook():
    if request.method == "GET" :
        submissions, assignment_names = getSubmissionsAssignmentsByUserIDandClassCode(session["user_id"], session["class_code"])
        class_name = getClassroomByCode(session["class_code"]).class_name
        return render_template("submissions/view_grades_student.html", submissions=submissions, assign_names=assignment_names, class_name=class_name, role = 1)

@submission_mod.route('/grade_submissions', methods=["GET","POST"])
def grade_submissions():
    if request.method == "GET" :
        session["assignment_id"] = request.args.get('id')
        submissions_data = getSubmissionsForAssign(session["assignment_id"])
        assigment = getAssignmentByID(session["assignment_id"])
        return render_template("submissions/edit_grades_teacher.html", assignment=assigment, submissions = submissions_data)


    if request.method == "POST" :
        submissions = getSubmissionByAssignID(session["assignment_id"])
        for submission in submissions:
            temp = getSubmissionByID(submission.id)
            temp.grade = request.form.get(str(submission.id))
            db.session.commit()
        return redirect(url_for("submission.view_submissions", id=session["assignment_id"]))

app/templates/submissions/edit_grades_teacher.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='submission.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}
{% block title %} Edit Grades {% endblock %}

{% block body %}
{% include "submission_nav_drawer.html" %}
<div id="assignment_title">
    <h3>{{assignment.title}} - Edit Grades</h3>
</div>
<div>
    <p id="assignment_score">Maximum Score - {{assignment.max_score}}</p>
</div>
  <main id="page_body">
    <table id="submission_table" style="width: 85%" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
            <tr>
                <th>S No.</th>
                <th>UID</th>
                <th>Name</th>
                <th>File</th>
                <th>Time</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
        <form action="{{url_for('submission.grade_submissions')}}" method="post">

        {% for submission in submissions%}
          <tr>
                <td>{{loop.index}}</td>
                <td>{{submission.uid}}</td>
                 <td>{{submission.user_name}}</td>
                 <td><a href="{{url_for('submission.view_file',filepath=submission.filepath, filename=submission.filename)}}">{{submission.filename}}</a></td>
                 <td>{{submission.timestamp}}</td>
                 <td><input id="grade_column" class="mdl-textfield__input" type="text" name="{{submission.id}}" value="{{submission.grade}}"></td>
          </tr>
        {% endfor %}
        <button id="save" type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            Save
        </button>
        </form>
      </tbody>
    </table>

  </main>
{% endblock %}

app/templates/submissions/submission_nav_drawer.html
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    {% include "header.html" %}
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{{url_for('submission.view_submissions', id=assignment.assignment_id)}}">View Submissions</a>
            <a class="mdl-navigation__link" href="{{url_for('submission.grade_submissions', id=assignment.assignment_id)}}">Grade Submissions</a>
            <a class="mdl-navigation__link" href="{{url_for('assignment.viewassign', id=assignment.assignment_id)}}">View Assignment Details</a>
            <a class="mdl-navigation__link" href="{{url_for('assignment.deleteassign', id=assignment.assignment_id)}}">Delete Assignment</a>
            <a class="mdl-navigation__link" href="{{url_for('assignment.assign', class_code=session['class_code'])}}">Back to Assignments</a>
        </nav>
    </div>
</div>

app/templates/submissions/upload_file_dialog.html
<button id="upload" type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
    Upload Files
</button>

<dialog id = "upload_file_dialog" class="mdl-dialog">
    <h5>Upload a File</h5><br>
    <form method="POST" action="{{url_for("submission.upload", id=assignment.assignment_id)}}" enctype="multipart/form-data">
        <div>
          <input type="file" name="file" required><br/><br/>
        </div>
      <div class="mdl-dialog__actions">
        <input type="submit" value="Upload" class="mdl-button upload"></button>
        <button type="button" class="mdl-button cancel">Cancel</button>
      </div>
    </form>
</dialog>

app/templates/submissions/view_grades_student.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='submission.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}
{% block title %} View Grades {% endblock %}

{% block body %}
{% include "./assignments/assign_nav_drawer.html" %}
<div id="assignment_title"><h3>{{class_name}} - Grades</h3> </div>
  <main id="page_body">
      <table id="submission_table" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
          <thead>
              <tr>
                  <th>S No.</th>
                  <th>Assignment Name</th>
                  <th>File Name</th>
                  <th>Grade</th>
                  <th>Maximum Score</th>
                  <th>Submitted On</th>
              </tr>
          </thead>
          <tbody>
              {% for submission in submissions%}
                <tr>
                  <td>{{loop.index}}</td>
                  <td>{{assign_names[submission.assignment_id][0]}}</td>
                  <td ><a href="{{url_for('submission.uploaded_file', assign_id=submission.assignment_id, filename=submission.filename)}}">{{submission.filename}}</a></td>
                  <td >{{submission.grade}}</td>
                  <td>{{assign_names[submission.assignment_id][1]}}</td>
                  <td>{{submission.timestamp}}</td>
                </tr>
              {% endfor %}
        </tbody>
  </main>
{% endblock %}

app/templates/submissions/view_submission_teacher.html
{% extends "layout.html" %}
{% block head %}
<link href="{{ url_for('static', filename='submission.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.teal-amber.min.css">
{% endblock %}
{% block title %} View Assignment {% endblock %}

{% block body %}
{% include "submission_nav_drawer.html" %}
<div id="assignment_title"><h3>{{assignment.title}} - Submissions</h3> </div>
<div><p id="assignment_score">Maximum Score - {{assignment.max_score}}</p> </div>
  <main id="page_body">
    <table id="submission_table" class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
        <thead>
            <tr>
                <th>S No.</th>
                <th>UID</th>
                <th>Name</th>
                <th>File</th>
                <th>Time</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
        {% for submission in submissions%}
          <tr>
                <td data-label="S No.">{{loop.index}}</td>
                <td data-label="UID">{{submission.uid}}</td>
                 <td data-label="Name">{{submission.user_name}}</td>
                 <td data-label="File"><a href="{{url_for('submission.view_file',filepath=submission.filepath, filename=submission.filename)}}">{{submission.filename}}</a></td>
                 <td data-label="Time">{{submission.timestamp}}</td>
                 <td data-label="Grade">{{submission.grade}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </main>
{% endblock %}